bg: S3C-3686 remove random delay from main code
scality/backbeat pull request #1373
Opened 2021-01-22 17:37 UTC by vrancurel

Instead use the feature from the mock. It makes the code more readable.

2021-01-22 17:37 UTC, bert-e commented
# Hello vrancurel,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/backbeat/bert-e/doc/user).





*Status report is not available.*

2021-01-22 17:37 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.1/bugfix/S3C-3686-remove-random-delays-from-codepath` with contents from `w/7.9/bugfix/S3C-3686-remove-random-delays-from-codepath`
and `development/8.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.1/bugfix/S3C-3686-remove-random-delays-from-codepath origin/development/8.1
 $ git merge origin/w/7.9/bugfix/S3C-3686-remove-random-delays-from-codepath
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/bugfix/S3C-3686-remove-random-delays-from-codepath
```

2021-01-22 17:39 UTC, vrancurel commented on package.json
> +    "zookeeper-mock": "^1.1.1"
Note the `npm` is not yet created so tests won't pass.

2021-01-22 19:07 UTC, miniscruff commented
No issues on this side of things, will re-review when the dependency is approved.

2021-01-22 19:08 UTC, miniscruff requested changes
Marking as needs work as it gives me the best notification when a change is made...

2021-01-22 21:34 UTC, bert-e commented
# History mismatch



Merge commit #fdd99b92b3815d017b92ced389b320939bcc6486 on the integration branch
`w/7.9/bugfix/S3C-3686-remove-random-delays-from-codepath` is merging a branch which is neither the current
branch `bugfix/S3C-3686-remove-random-delays-from-codepath` nor the development branch
`development/7.9`.

It is likely due to a rebase of the branch `bugfix/S3C-3686-remove-random-delays-from-codepath` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2021-01-22 21:43 UTC, miniscruff approved these changes
Approving even though the dependency isn't updated as I already reviewed that one too

2021-01-23 01:32 UTC, naren-scality approved these changes

2021-01-25 22:58 UTC, vrancurel commented
/reset

2021-01-25 22:58 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2021-01-25 22:58 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.1/bugfix/S3C-3686-remove-random-delays-from-codepath` with contents from `w/7.9/bugfix/S3C-3686-remove-random-delays-from-codepath`
and `development/8.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.1/bugfix/S3C-3686-remove-random-delays-from-codepath origin/development/8.1
 $ git merge origin/w/7.9/bugfix/S3C-3686-remove-random-delays-from-codepath
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/bugfix/S3C-3686-remove-random-delays-from-codepath
```

2021-01-25 23:16 UTC, jonathan-gramain approved these changes

2021-01-25 23:19 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-3686-remove-random-delays-from-codepath` into
`development/7.4`
* [w/7.9/bugfix/S3C-3686-remove-random-delays-from-codepath](https://github.com/scality/backbeat/compare/development/7.9...w/7.9/bugfix/S3C-3686-remove-random-delays-from-codepath) will be merged into `development/7.9` (pull request #1380)
* [w/8.1/bugfix/S3C-3686-remove-random-delays-from-codepath](https://github.com/scality/backbeat/compare/development/8.1...w/8.1/bugfix/S3C-3686-remove-random-delays-from-codepath) will be merged into `development/8.1` (pull request #1381)
* [w/8.2/bugfix/S3C-3686-remove-random-delays-from-codepath](https://github.com/scality/backbeat/compare/development/8.2...w/8.2/bugfix/S3C-3686-remove-random-delays-from-codepath) will be merged into `development/8.2` (pull request #1382)





*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2021-01-25 23:19 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @jonathan-gramain.

2021-01-25 23:20 UTC, vrancurel commented
/approve

2021-01-26 01:04 UTC, vrancurel commented
/reset

2021-01-26 01:04 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2021-01-26 01:04 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.1/bugfix/S3C-3686-remove-random-delays-from-codepath` with contents from `w/7.9/bugfix/S3C-3686-remove-random-delays-from-codepath`
and `development/8.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.1/bugfix/S3C-3686-remove-random-delays-from-codepath origin/development/8.1
 $ git merge origin/w/7.9/bugfix/S3C-3686-remove-random-delays-from-codepath
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/bugfix/S3C-3686-remove-random-delays-from-codepath
```





*The following options are set:* **approve**

2021-01-26 01:19 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-3686-remove-random-delays-from-codepath` into
`development/7.4`
* [w/7.9/bugfix/S3C-3686-remove-random-delays-from-codepath](https://github.com/scality/backbeat/compare/development/7.9...w/7.9/bugfix/S3C-3686-remove-random-delays-from-codepath) will be merged into `development/7.9` (pull request #1389)
* [w/8.1/bugfix/S3C-3686-remove-random-delays-from-codepath](https://github.com/scality/backbeat/compare/development/8.1...w/8.1/bugfix/S3C-3686-remove-random-delays-from-codepath) will be merged into `development/8.1` (pull request #1390)
* [w/8.2/bugfix/S3C-3686-remove-random-delays-from-codepath](https://github.com/scality/backbeat/compare/development/8.2...w/8.2/bugfix/S3C-3686-remove-random-delays-from-codepath) will be merged into `development/8.2` (pull request #1391)





*Follow* integration pull requests if you would like to be notified of
build statuses by email.







*The following options are set:* **approve**

2021-01-26 01:32 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/7.9`

* :heavy_check_mark: `development/8.1`

* :heavy_check_mark: `development/8.2`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-01-26 01:47 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/7.9`

* :heavy_check_mark: `development/8.1`

* :heavy_check_mark: `development/8.2`




Please check the status of the associated issue S3C-3686.

Goodbye vrancurel.

2021-01-26 01:47 UTC, merged