ft: support specifying partition in entries
scality/backbeat pull request #149
Opened 2017-12-07 21:31 UTC by philipyoo

To support deep healthcheck, where I want to produce to all
partitions, allow for specifying a partition within an entry.

2017-12-12 19:34 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2017-12-12 19:56 UTC, jonathan-gramain commented on lib/BackbeatProducer.js
> +            } else if (item.partition && this._partition === undefined) {
You can get rid of the `else`.

Minor style comment: the tests would be simpler and more understandable if you use the following sequence instead:

```
if (this._partition) { return ...}
if (item.partition) { return ...}
return {...}
```

2017-12-13 00:26 UTC, jonathan-gramain submitted a review, later dismissed

2017-12-13 00:35 UTC, rahulreddy requested changes

2017-12-13 00:35 UTC, rahulreddy commented on lib/BackbeatProducer.js
> +            if (item.partition) {
This needs to be `if (item.partition !== undefined)` since partition can be `0`.

2017-12-13 00:35 UTC, rahulreddy commented on lib/BackbeatProducer.js
> +            if (this._partition) {
Same here `if (this._partition !== undefined)`

2017-12-13 20:35 UTC, philipyoo commented
Sorry, one additional field I'd like to add for entries that have explicit partition declared. Added PR: 79de399

I realize when parsing entries in `QueueProcessor.processKafkaEntry`, I want to catch entries specific to deep healthcheck. By setting a `key` property for these entries, I can catch and ignore deep healthcheck entries.

2017-12-19 02:32 UTC, jonathan-gramain commented
@philipyoo I had a similar issue with testing to inject artificial messages and ensure the consumer would receive them, while not disturbing the regular backbeat consumer too much. For this I added a "bootstrapId" field to the JSON message, and backbeat consumer skips those entries (actually sends back an error but keeps going with next entries).

In case of healthchecks, we do not want to error but simply skip them in regular processing. I'm thinking `key` can be confused with other fields with the same name (object key, kafka key...), hence maybe just setting a `"healthcheck": true` or `"healthcheckKey": "foo"` field can do the trick, but make sure that it's clearly visible somehow that the entry comes from the healthcheck to ease troubleshooting.

2018-02-18 20:41 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-02-18 20:44 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-02-18 20:44 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-02-18 20:46 UTC, philipyoo commented
As @jonathan-gramain commented, rather than catching deep healthcheck entries by the key property, instead putting the identifier within the message property and filtering within `QueueEntry.createFromKafkaEntry`

2018-05-21 17:42 UTC, philipyoo commented
Implementation has changed with switch to node-rdkafka. Plan is now to produce to Kafka directly using the same topic and consumer group.

2018-05-21 17:42 UTC, closed without merging