BB-63 Missing readiness probe routes
scality/backbeat pull request #1950
Opened 2021-09-23 19:30 UTC by nicolas2bert

2021-09-23 19:30 UTC, bert-e commented
# Hello nicolas2bert,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/backbeat/bert-e/doc/user).





*Status report is not available.*

2021-09-23 19:30 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue BB-63 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.3.0`


Please check the `Fix Version/s` of BB-63, or the target
branch of this pull request.

2021-09-23 19:30 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue BB-63 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.2.9`

* `8.3.0`


Please check the `Fix Version/s` of BB-63, or the target
branch of this pull request.

2021-09-23 19:31 UTC, miniscruff approved these changes

2021-09-23 19:31 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/BB-63/probe` into
`development/8.2`
* [w/8.3/bugfix/BB-63/probe](https://github.com/scality/backbeat/compare/development/8.3...w/8.3/bugfix/BB-63/probe) will be merged into `development/8.3` (pull request #1951)



The following branches will **NOT** be impacted:

* `development/7.10`
* `development/7.4`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2021-09-23 19:31 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-09-23 19:32 UTC, naren-rajendran commented on bin/queuePopulator.js
> +                DEFAULT_READY_ROUTE,
```suggestion
                [DEFAULT_LIVE_ROUTE, DEFAULT_READY_ROUTE],
```

2021-09-23 19:33 UTC, naren-rajendran commented on extensions/replication/replicationStatusProcessor/task.js
>                          DEFAULT_LIVE_ROUTE,
```suggestion
                        [DEFAULT_LIVE_ROUTE, DEFAULT_READY_ROUTE],
```

2021-09-23 19:37 UTC, bert-e commented
# History mismatch



Merge commit #d8ddb823418c5375d7e1900ec25233519b31182b on the integration branch
`w/8.3/bugfix/BB-63/probe` is merging a branch which is neither the current
branch `bugfix/BB-63/probe` nor the development branch
`development/8.3`.

It is likely due to a rebase of the branch `bugfix/BB-63/probe` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2021-09-23 19:38 UTC, naren-rajendran requested changes
ProbeServer.addHandler takes only two arguments

2021-09-23 19:38 UTC, naren-rajendran approved these changes

2021-09-23 19:39 UTC, nicolas2bert commented
@bert-e reset

2021-09-23 19:40 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2021-09-23 19:40 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/BB-63/probe` into
`development/8.2`
* [w/8.3/bugfix/BB-63/probe](https://github.com/scality/backbeat/compare/development/8.3...w/8.3/bugfix/BB-63/probe) will be merged into `development/8.3` (pull request #1953)



The following branches will **NOT** be impacted:

* `development/7.10`
* `development/7.4`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2021-09-23 19:40 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-09-24 16:17 UTC, rahulreddy commented
/bypass_build_status

2021-09-24 16:17 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers











*The following options are set:* **bypass_build_status**

2021-09-24 16:18 UTC, nicolas2bert commented
@bert-e approve

2021-09-24 16:18 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.2`

* :heavy_check_mark: `development/8.3`



The following branches will **NOT** be impacted:

* `development/7.10`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **bypass_build_status, approve**

2021-09-24 16:37 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.2`

* :heavy_check_mark: `development/8.3`



The following branches have **NOT** changed:

* `development/7.10`
* `development/7.4`



Please check the status of the associated issue BB-63.

Goodbye nicolas2bert.

2021-09-24 16:37 UTC, merged