BB-148: add processBuckets callback function type check
scality/backbeat pull request #2133
Opened 2022-04-02 05:24 UTC by alexanderchan-scality

add callback type check before invoking in processBuckets method.
cron scheduler does not pass a function type as a parameter to the
processBuckets callback.

2022-04-02 05:24 UTC, bert-e commented
# Hello alexanderchan-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/backbeat/bert-e/doc/user).





*Status report is not available.*

2022-04-02 05:25 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue BB-148 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.3.12`


Please check the `Fix Version/s` of BB-148, or the target
branch of this pull request.

2022-04-02 06:16 UTC, naren-rajendran approved these changes

2022-04-04 16:27 UTC, miniscruff approved these changes

2022-04-04 17:04 UTC, RachedBenMustapha requested changes
If the signature of cron callbacks changed, the it should be updated at the signature level and in the tests, rather than checking the type at runtime.

2022-04-04 20:24 UTC, bert-e commented
# Branches have diverged



This pull request's source branch `bugfix/BB-148/addProcessBucketsCallbackFunctionCheck` has diverged from
`development/8.3` by more than 50 commits.

To avoid any integration risks, please re-synchronize them using one of the
following solutions:

* Merge `origin/development/8.3` into `bugfix/BB-148/addProcessBucketsCallbackFunctionCheck`
* Rebase `bugfix/BB-148/addProcessBucketsCallbackFunctionCheck` onto `origin/development/8.3`

Note: If you choose to rebase, you may have to ask me to rebuild
integration branches using the `reset` command.

2022-04-04 21:04 UTC, miniscruff approved these changes

2022-04-04 21:43 UTC, RachedBenMustapha approved these changes

2022-04-04 22:44 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue BB-148 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `7.10.4`

* `8.2.14`

* `8.3.12`


Please check the `Fix Version/s` of BB-148, or the target
branch of this pull request.

2022-04-04 22:50 UTC, alexanderchan-scality commented
ping

2022-04-04 22:50 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/BB-148/addProcessBucketsCallbackFunctionCheck` into
`development/7.10`
* [w/8.2/bugfix/BB-148/addProcessBucketsCallbackFunctionCheck](https://github.com/scality/backbeat/compare/development/8.2...w/8.2/bugfix/BB-148/addProcessBucketsCallbackFunctionCheck) will be merged into `development/8.2` (pull request #2134)
* [w/8.3/bugfix/BB-148/addProcessBucketsCallbackFunctionCheck](https://github.com/scality/backbeat/compare/development/8.3...w/8.3/bugfix/BB-148/addProcessBucketsCallbackFunctionCheck) will be merged into `development/8.3` (pull request #2135)



The following branches will **NOT** be impacted:

* `development/7.4`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2022-04-04 22:50 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-04-05 00:25 UTC, alexanderchan-scality commented
/approve

2022-04-05 00:26 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/7.10`

* :heavy_check_mark: `development/8.2`

* :heavy_check_mark: `development/8.3`



The following branches will **NOT** be impacted:

* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-04-05 00:26 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/7.10`

* :heavy_check_mark: `development/8.2`

* :heavy_check_mark: `development/8.3`



The following branches have **NOT** changed:

* `development/7.4`



Please check the status of the associated issue BB-148.

Goodbye alexanderchan-scality.

2022-04-05 00:26 UTC, merged