BB-175: update GC processes to use service accounts
scality/backbeat pull request #2191
Opened 2022-05-20 16:19 UTC by alexanderchan-scality

2022-05-20 16:20 UTC, bert-e commented
# Hello alexanderchan-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/backbeat/bert-e/doc/user).





*Status report is not available.*

2022-05-20 16:20 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue BB-175 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.4.2`


Please check the `Fix Version/s` of BB-175, or the target
branch of this pull request.

2022-05-23 16:01 UTC, nicolas2bert requested changes

2022-05-23 16:01 UTC, nicolas2bert commented on extensions/lifecycle/tasks/LifecycleUpdateTransitionTask.js
> +        const { bucket, key, version, eTag, accountId } = entry.getAttribute('target');
`target.owner` is needed to get the [backbeat client](https://github.com/scality/backbeat/pull/2191/files#diff-7beaf0ffcd262dad5a78c1b25cb7d54b9ac577441b372167f96d8c182be8fcf7R23) for the Garbage Collector task.

2022-05-25 18:54 UTC, nicolas2bert approved these changes

2022-05-25 18:56 UTC, miniscruff approved these changes

2022-05-25 19:03 UTC, alexanderchan-scality commented
/approve

2022-05-25 19:03 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue BB-175 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.4.2`


Please check the `Fix Version/s` of BB-175, or the target
branch of this pull request.




*The following options are set:* **approve**

2022-05-25 21:38 UTC, alexanderchan-scality commented
ping

2022-05-25 21:38 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.4`



The following branches will **NOT** be impacted:

* `development/7.10`
* `development/7.4`
* `development/8.2`
* `development/8.3`
* `stabilization/7.10.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-05-25 21:39 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.4`



The following branches have **NOT** changed:

* `development/7.10`
* `development/7.4`
* `development/8.2`
* `development/8.3`
* `stabilization/7.10.4`



Please check the status of the associated issue BB-175.

Goodbye alexanderchan-scality.

2022-05-25 21:39 UTC, merged