Remove default behaviour of selecting the first cold location on expi…
scality/backbeat pull request #2461
Opened 2023-10-20 14:47 UTC by Kerkesni

…ration of cold objects

We don’t need this logic anymore as sorbet always sets the location name and this might introduce unwanted behaviours when having multiple locations

Issue: BB-417

2023-10-20 14:47 UTC, bert-e commented
# Hello kerkesni,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://bert-e.scality.net/scality/backbeat/doc/user).





*Status report is not available.*

2023-10-20 14:47 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2023-10-23 10:30 UTC, francoisferrand commented on extensions/lifecycle/tasks/LifecycleUpdateExpirationTask.js
> +                const coldLocation = entry.getAttribute('target.location');
this should be done before retrieving metadata?

2023-10-23 10:34 UTC, KillianG requested changes

2023-10-23 10:34 UTC, KillianG commented on tests/unit/lifecycle/LifecycleUpdateExpirationTask.spec.js
> +    it.only('should throw an error when location is not specified', done => {
remove `.only`

2023-10-23 10:34 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @killiang

2023-10-24 12:58 UTC, KillianG approved these changes

2023-10-24 12:58 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2023-10-27 14:18 UTC, francoisferrand approved these changes

2023-10-27 14:47 UTC, Kerkesni commented
/approve

2023-10-27 14:47 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.7`



The following branches will **NOT** be impacted:

* `development/7.10`
* `development/7.4`
* `development/7.70`
* `development/8.5`
* `development/8.6`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2023-10-27 15:21 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.7`



The following branches have **NOT** changed:

* `development/7.10`
* `development/7.4`
* `development/7.70`
* `development/8.5`
* `development/8.6`



Please check the status of the associated issue BB-417.

Goodbye kerkesni.

2023-10-27 15:21 UTC, merged