feature/ZENKO-437 Add backbeat health checks
scality/backbeat pull request #323
Opened 2018-06-15 21:59 UTC by tmacro

2018-06-15 21:59 UTC, bert-e commented
# Hello tmacro,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-06-15 21:59 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers

2018-06-15 22:58 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-15 22:58 UTC, ironman-machine commented
```
CONFLICT (content): Merge conflict in extensions/replication/queueProcessor/task.js
```

2018-06-15 22:58 UTC, bert-e commented
# Conflict




There is a conflict between your branch `feature/ZENKO-437_Backbeat_Readiness_Probes` and the
destination branch `development/8.0`.

Please resolve the conflict on **the feature branch** (`feature/ZENKO-437_Backbeat_Readiness_Probes`).

```
#!bash
 $ git fetch
 $ git checkout origin/feature/ZENKO-437_Backbeat_Readiness_Probes
 $ git merge origin/development/8.0
 $ # <intense conflict resolution>
 $ git push origin HEAD:feature/ZENKO-437_Backbeat_Readiness_Probes
```

2018-06-18 20:28 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-18 20:28 UTC, ironman-machine commented
```
CONFLICT (content): Merge conflict in extensions/replication/replicationStatusProcessor/task.js
CONFLICT (content): Merge conflict in extensions/replication/queueProcessor/task.js
```

2018-06-18 20:37 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-18 20:37 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers

2018-06-18 22:00 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-20 18:02 UTC, jonathan-gramain commented on bin/queuePopulator.js
> +            if (state.code === 3) {
You should use the symbolic constant exposed by the zookeeper client module (may be `zookeeper.State.SYNC_CONNECTED`?)

2018-06-20 18:02 UTC, jonathan-gramain commented on extensions/lifecycle/conductor/LifecycleConductor.js
> +        return this._producer.isReady() && state && state.code === 3;
same for the symbolic constant

2018-06-20 18:02 UTC, jonathan-gramain commented on extensions/lifecycle/lifecycleConsumer/task.js
>          log.info('management init done');
You can move that log line before `healthServer.onReadyCheck()` since it relates to the management layer initialization.

2018-06-20 18:02 UTC, jonathan-gramain commented on extensions/lifecycle/lifecycleProducer/LifecycleProducer.js
> +        return this._bucketProducer.isReady() && this._objectProducer.isReady();
Maybe you also want to check `this._consumer.isReady()`?

2018-06-20 18:02 UTC, jonathan-gramain commented on extensions/lifecycle/lifecycleProducer/task.js
>          logger.info('management init done');
move the log line above `healthServer.onReadyCheck()`

2018-06-20 18:15 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-20 18:15 UTC, ironman-machine commented
```
CONFLICT (add/add): Merge conflict in tests/unit/api/BackbeatRequest.spec.js
CONFLICT (add/add): Merge conflict in tests/unit/api/BackbeatAPI.spec.js
CONFLICT (add/add): Merge conflict in tests/functional/api/BackbeatServer.js
CONFLICT (add/add): Merge conflict in package.json
CONFLICT (add/add): Merge conflict in lib/queuePopulator/QueuePopulator.js
CONFLICT (add/add): Merge conflict in lib/api/BackbeatServer.js
CONFLICT (add/add): Merge conflict in lib/api/BackbeatRequest.js
CONFLICT (add/add): Merge conflict in lib/api/BackbeatAPI.js
CONFLICT (add/add): Merge conflict in lib/MetricsConsumer.js
CONFLICT (add/add): Merge conflict in lib/BackbeatConsumer.js
CONFLICT (add/add): Merge conflict in index.js
CONFLICT (add/add): Merge conflict in extensions/replication/replicationStatusProcessor/task.js
CONFLICT (add/add): Merge conflict in extensions/replication/replicationStatusProcessor/ReplicationStatusProcessor.js
CONFLICT (add/add): Merge conflict in extensions/replication/queueProcessor/task.js
CONFLICT (add/add): Merge conflict in extensions/replication/queueProcessor/QueueProcessor.js
CONFLICT (add/add): Merge conflict in extensions/replication/failedCRR/FailedCRRProducer.js
CONFLICT (add/add): Merge conflict in extensions/lifecycle/lifecycleProducer/task.js
CONFLICT (add/add): Merge conflict in extensions/lifecycle/lifecycleProducer/LifecycleProducer.js
CONFLICT (add/add): Merge conflict in extensions/lifecycle/lifecycleConsumer/task.js
CONFLICT (add/add): Merge conflict in extensions/lifecycle/lifecycleConsumer/LifecycleConsumer.js
CONFLICT (add/add): Merge conflict in extensions/lifecycle/conductor/service.js
CONFLICT (add/add): Merge conflict in extensions/lifecycle/conductor/LifecycleConductor.js
CONFLICT (add/add): Merge conflict in eve/workers/unit_and_feature_tests/run_server_tests.bash
CONFLICT (add/add): Merge conflict in circle.yml
CONFLICT (add/add): Merge conflict in bin/queuePopulator.js
```

2018-06-20 18:31 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-26 18:39 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-26 18:41 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-26 19:30 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-26 19:36 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-26 20:28 UTC, philipyoo submitted a review, later dismissed
nice 👍

2018-06-26 20:28 UTC, philipyoo commented on extensions/replication/replicationStatusProcessor/task.js
> +const { initManagement } = require('../../../lib/management');
path here should include `/index`

2018-06-26 20:53 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-26 20:53 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-26 20:57 UTC, philipyoo submitted a review, later dismissed

2018-06-26 21:14 UTC, JianqinWang commented
Please rebase the branch, development/8.0 has a recent commit that fixes the failing CI tests iirc @philipyoo

2018-06-26 21:15 UTC, jonathan-gramain requested changes
We have a new GC service now (only one consumer process!) do you want to add support there as well to avoid a later PR? :yum:

2018-06-26 21:15 UTC, jonathan-gramain commented on bin/queuePopulator.js
> +const healthServer = new HealthProbeServer({ bindAddress: '0.0.0.0',
Ideally `bindAddress` and `port` should be taken from config.json.

2018-06-26 21:15 UTC, jonathan-gramain commented on bin/queuePopulator.js
> +            log.error(`Zookeeper is not connected! ${state}`);
minor: could be better to log state as a log object in second argument (with `{ state }`)

2018-06-26 21:18 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-26 21:18 UTC, ironman-machine commented
```
CONFLICT (add/add): Merge conflict in tests/functional/api/BackbeatServer.js
CONFLICT (add/add): Merge conflict in package.json
CONFLICT (add/add): Merge conflict in lib/util/getFailedCRRKey.js
CONFLICT (add/add): Merge conflict in lib/config/configItems.joi.js
CONFLICT (add/add): Merge conflict in lib/clients/backbeat-2017-07-01.api.json
CONFLICT (add/add): Merge conflict in lib/api/BackbeatAPI.js
CONFLICT (add/add): Merge conflict in extensions/replication/replicationStatusProcessor/ReplicationStatusProcessor.js
CONFLICT (add/add): Merge conflict in extensions/replication/ReplicationQueuePopulator.js
CONFLICT (add/add): Merge conflict in extensions/lifecycle/lifecycleConsumer/LifecycleConsumer.js
CONFLICT (add/add): Merge conflict in eve/workers/unit_and_feature_tests/run_server_tests.bash
CONFLICT (add/add): Merge conflict in docker-entrypoint.sh
CONFLICT (add/add): Merge conflict in conf/config.json
CONFLICT (add/add): Merge conflict in circle.yml
```

2018-06-26 21:18 UTC, bert-e commented
# Conflict




There is a conflict between your branch `feature/ZENKO-437_Backbeat_Readiness_Probes` and the
destination branch `development/8.0`.

Please resolve the conflict on **the feature branch** (`feature/ZENKO-437_Backbeat_Readiness_Probes`).

```
#!bash
 $ git fetch
 $ git checkout origin/feature/ZENKO-437_Backbeat_Readiness_Probes
 $ git merge origin/development/8.0
 $ # <intense conflict resolution>
 $ git push origin HEAD:feature/ZENKO-437_Backbeat_Readiness_Probes
```

2018-06-26 21:22 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-26 21:22 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers

2018-06-26 21:25 UTC, closed without merging

2018-06-26 21:25 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.