ft: ZENKO-587 Apply preferred read location in backbeat management
scality/backbeat pull request #334
Opened 2018-06-26 17:53 UTC by nicolas2bert

2018-06-26 18:27 UTC, rachedbenmustapha requested changes

2018-06-26 18:27 UTC, RachedBenMustapha commented on extensions/replication/management.js
> +                            if (wf.destination.preferredReadLocation &&
The `preferredReadLocation` null-check is redundant

2018-06-26 18:47 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-26 22:52 UTC, jonathan-gramain approved these changes
:+1:

2018-06-27 00:01 UTC, rachedbenmustapha approved these changes

2018-06-27 00:03 UTC, closed without merging