improvement: Add dump.rdb to gitignore
scality/backbeat pull request #363
Opened 2018-07-05 21:24 UTC by bennettbuchanan

🍹

2018-07-05 21:24 UTC, bert-e commented
# Hello bennettbuchanan,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-07-05 21:24 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers

2018-07-05 21:28 UTC, anurag4DSB approved these changes

2018-07-05 21:34 UTC, dora-korpar approved these changes

2018-07-05 21:44 UTC, rahulreddy requested changes
You can use `*.rdb` which picks up rdb with any name

2018-07-05 21:53 UTC, bennettbuchanan commented
Updated to include all .rdb files. @rahulreddy

2018-07-05 22:17 UTC, jonathan-gramain approved these changes

2018-07-05 22:18 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/backbeat/commit/a8c752151ecd69da48f31d6961accb8b13c4b6db) did not succeed in branch improvement/update-gitignore.

2018-07-05 22:36 UTC, rahulreddy approved these changes

2018-07-06 20:18 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.0`



The following branches will **NOT** be impacted:

* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-07-06 20:18 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.0`



The following branches have **NOT** changed:

* `development/7.4`



Please check the status of the associated issue None.

Goodbye bennettbuchanan.

2018-07-06 20:18 UTC, merged