ft: increase metrics expiry window to 24hrs
scality/backbeat pull request #403
Opened 2018-08-07 19:54 UTC by philipyoo

Relies on https://github.com/scality/Arsenal/pull/549

2018-08-07 19:54 UTC, bert-e commented
# Hello philipyoo,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-08-07 19:54 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @vrancurel

* @rahulreddy

* @bennettbuchanan

* @jonathan-gramain

2018-08-07 21:39 UTC, rahulreddy requested changes
Looks like you changed a lot more than increasing the expiry i.e. getting rid of OBJECT_MONITORING_EXPIRY for example, which is ok. Can you add this as a comment or separate them into commits and add it as comment body explaining the change?

2018-08-08 17:08 UTC, philipyoo commented
Ok sounds good 👍 Will add as a comment

2018-08-08 17:47 UTC, philipyoo commented
@bert-e wait

2018-08-08 17:48 UTC, JianqinWang approved these changes

2018-08-08 18:04 UTC, bennettbuchanan approved these changes
:shipit:

2018-08-08 18:04 UTC, bennettbuchanan commented on docs/metrics.md
> +A single-location CRR entry produces up to six keys in total. The data points
👏

2018-08-08 18:04 UTC, bennettbuchanan commented on lib/MetricsConsumer.js
> +    _sendRequest(key, value) {
This makes for a really nice cleanup!

2018-08-08 22:37 UTC, jonathan-gramain approved these changes

2018-08-09 00:46 UTC, rahulreddy approved these changes

2018-08-09 00:47 UTC, rahulreddy commented
@bert-e status

2018-08-09 00:47 UTC, bert-e commented
# Status





*Status report is not available.*






*The following options are set:* **wait**

2018-08-09 00:47 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.0`



The following branches will **NOT** be impacted:

* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-08-09 00:53 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.0`



The following branches have **NOT** changed:

* `development/7.4`



Please check the status of the associated issue ZENKO-925.

Goodbye philipyoo.

2018-08-09 00:53 UTC, merged