feature: ZENKO-1376 tests for bbClient ingestion methods
scality/backbeat pull request #550
Opened 2018-12-13 00:18 UTC by JianqinWang

2018-12-13 00:18 UTC, bert-e commented
# Hello jianqinwang,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-12-13 00:18 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @jonathan-gramain

* @bennettbuchanan

* @rahulreddy

* @vrancurel

2018-12-13 17:59 UTC, tmacro approved these changes

2018-12-13 18:15 UTC, rahulreddy requested changes

2018-12-13 18:15 UTC, rahulreddy commented on tests/utils/MockMetadataServer.js
> +        (/\/_\/metadata\/default\/bucket\/[a-z0-9]{3,63}\/[a-z0-9]{3,63}/
Can you put these RegEx patterns in variables and add a one-liner comment mentioning what routes they correspond to?

2018-12-13 18:18 UTC, bennettbuchanan commented on tests/functional/lib/BackbeatClient.js
> +            assert.strictEqual(typeof data.info.start, 'number');
Do we not also want to assert the values as was done with the `mockLogs`?

2018-12-13 18:18 UTC, bennettbuchanan commented on tests/functional/lib/BackbeatClient.js
> +            assert.strictEqual(data.metadata, 'dogsAreGood');
👍

2018-12-13 18:20 UTC, philipyoo commented on eve/main.yml
> +          name: run feature ingestion tests
👍

2018-12-14 19:01 UTC, philipyoo approved these changes

2018-12-14 20:23 UTC, rahulreddy requested changes
Sorry for another round of requesting changes but changing the tests to test values would be nice.

2018-12-14 20:23 UTC, rahulreddy commented on tests/functional/lib/BackbeatClient.js
> +            data.Contents.forEach(object => {
Same thing here, use build the expected object and assert using `deepStrictEqual`

2018-12-14 20:23 UTC, rahulreddy commented on tests/functional/lib/BackbeatClient.js
> +            assert.strictEqual(typeof data.acl, 'object');
I suggest building the expected object using the json and assert using the `deepStrictEqual` method. This way you are validating type and value at the same time.

2018-12-14 20:23 UTC, rahulreddy commented on tests/utils/MockMetadataServer.js
> +const bucketListURL = '\\/_\\/metadata\\/admin\\/raft_sessions\\/[1-8]' +
💯

2018-12-14 23:24 UTC, rahulreddy approved these changes

2018-12-15 01:13 UTC, JianqinWang commented
@bert-e approve

2018-12-15 01:13 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.1`



The following branches will **NOT** be impacted:

* `development/7.4`
* `development/8.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2018-12-15 01:13 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.1`



The following branches have **NOT** changed:

* `development/7.4`
* `development/8.0`



Please check the status of the associated issue ZENKO-1376.

Goodbye jianqinwang.

2018-12-15 01:13 UTC, merged