ft: ZENKO-1448 ingestion location cleanup
scality/backbeat pull request #657
Opened 2019-03-20 23:48 UTC by philipyoo

Sits on top of https://github.com/scality/backbeat/pull/650

When a user removes an ingestion bucket, we should cleanup the bucket path in zookeeper.
In zookeeper, the path is prefixed like: `/ingestion/<bucket>`
This path has nodes that hold information about the snapshot phase and log offset

From a user perspective, in order for a cleanup to occur, they would need to remove all object versions from their Zenko bucket. This will remove object versions from their s3c bucket as well. Then, they can remove the Zenko bucket. The cleanup will occur after deletion of Zenko bucket and before we try and call `processLogEntries` for that given ingestion bucket.

2019-03-22 23:27 UTC, rahulreddy approved these changes

2019-03-25 18:14 UTC, JianqinWang approved these changes

2019-03-25 18:45 UTC, rahulreddy requested changes
The only thing I would suggest is adding logs in methods where there aren't any. It will help us debug easily when there is an issue. Make sure you add `method` param to the logs to give context.

2019-03-25 18:45 UTC, rahulreddy commented on extensions/mongoProcessor/MongoQueueProcessor.js
> +        async.parallel([
Add a log here that the consumer is being stopped and another log if we are skipping because there was no consumer.

2019-03-25 20:36 UTC, rahulreddy approved these changes

2019-03-25 21:13 UTC, bert-e commented
# Hello philipyoo,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/backbeat/bert-e/doc/user).





*Status report is not available.*

2019-03-25 21:13 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @bennettbuchanan

* @vrancurel

* @jonathan-gramain

2019-03-25 21:14 UTC, philipyoo commented
@bert-e approve

2019-03-25 21:14 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.1`



The following branches will **NOT** be impacted:

* `development/7.4`
* `development/7.5`
* `development/8.0`
* `stabilization/7.4.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-03-25 21:27 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.1`



The following branches have **NOT** changed:

* `development/7.4`
* `development/7.5`
* `development/8.0`
* `stabilization/7.4.3`



Please check the status of the associated issue ZENKO-1448.

Goodbye philipyoo.

2019-03-25 21:27 UTC, merged